// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbTBUba7mlZrdIqZOiLx8nTBCPJmzGENM',
    appId: '1:657200537189:web:c1c6c98abff5351b09308c',
    messagingSenderId: '657200537189',
    projectId: 'calm-mind-a079d',
    authDomain: 'calm-mind-a079d.firebaseapp.com',
    storageBucket: 'calm-mind-a079d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaSPwZSKWe16_-Vza8gXX88d0IDaCV38',
    appId: '1:657200537189:android:bc493b36df2d199409308c',
    messagingSenderId: '657200537189',
    projectId: 'calm-mind-a079d',
    storageBucket: 'calm-mind-a079d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZBBOG4p9ZgUYk-PzfaKoUMD9iWy_fPM',
    appId: '1:657200537189:ios:6bb37ec98cf98f6209308c',
    messagingSenderId: '657200537189',
    projectId: 'calm-mind-a079d',
    storageBucket: 'calm-mind-a079d.firebasestorage.app',
    iosBundleId: 'com.example.myFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZBBOG4p9ZgUYk-PzfaKoUMD9iWy_fPM',
    appId: '1:657200537189:ios:6bb37ec98cf98f6209308c',
    messagingSenderId: '657200537189',
    projectId: 'calm-mind-a079d',
    storageBucket: 'calm-mind-a079d.firebasestorage.app',
    iosBundleId: 'com.example.myFyp',
  );
}
